name       : haskell-asn1-encoding
version    : 0.9.6
release    : 3
source     :
    - https://hackage.haskell.org/package/asn1-encoding-0.9.6/asn1-encoding-0.9.6.tar.gz : d9f8deabd3b908e5cf83c0d813c08dc0143b3ec1c0d97f660d2cfa02c1c8da0a
license    : BSD-3-Clause
component  : programming.haskell
summary    : ASN1 data reader and writer in raw form with supports for high level forms of ASN1 (BER, and DER).
description: |
    ASN1 data reader and writer in raw form with supports for high level forms of ASN1 (BER, and DER).
builddeps  :
    - haskell-asn1-types-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-asn1-types-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
