name       : haskell-asn1-encoding
version    : 0.9.5
release    : 1
source     :
    - http://hackage.haskell.org/package/asn1-encoding-0.9.5/asn1-encoding-0.9.5.tar.gz : 1e863bfd363f6c3760cc80f2c0d422e17845a9f79fe006030db202ecab5aaf29
license    : BSD-3-Clause
component  : programming.haskell
summary    : ASN1 data reader and writer in raw form with supports for high level forms of ASN1 (BER, and DER).
description: |
    ASN1 data reader and writer in raw form with supports for high level forms of ASN1 (BER, and DER).
builddeps  :
    - haskell-asn1-types
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
